apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sonarqube
  labels:
    app: sonarqube
    name: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
        - name: sonarqube
          image: xxxxxxxxxxxx.dkr.ecr.xxxxxxxxxxxxxx.amazonaws.com/sonarqube:9.9.4.87374
          resources:
            requests:
              cpu: 500m
              memory: 1024Mi
            limits:
              cpu: 2000m
              memory: 2048Mi
            volumeMounts:
              - mountPath: /opt/sonarqube/data/
                name: sonar-data
              - mountPath: /opt/sonarqube/extensions/
                name: sonar-data
            env:
              - name: SONARQUBE_JDBC_USERNAME
                value: myuser
              - name: SONARQUBE_JDBC_URL
                value: jdbc:postgresql://xxxxxx.xxxxxxxxxxxxxx.rds.amazonaws.com:5432/db
              - name: SONARQUBE_JDBC_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: postgres
                    key: mypass
            ports:
              - containerPort: 9000
                protocol: TCP
      volumes:
        - name: sonar-data
          persistentVolumeClaim:
            claimName: efs-claim