apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sonarqube
  labels:
    app: sonarqube
    name: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
        - name: sonarqube
          image: sonarqube:lts-community
          resources:
            requests:
              cpu: 500m
              memory: 1024Mi
            limits:
              cpu: 2000m
              memory: 2048Mi
            volumeMounts:
            - mountPath: "/opt/sonarqube/data/"
              name: sonar-data
            - mountPath: "/opt/sonarqube/extensions/"
              name: sonar-data
            env:
              - name: "SONARQUBE_JDBC_USERNAME"
                value: "postgres"
              - name: "SONARQUBE_JDBC_URL"
                value: "jdbc:postgresql://postgresql-dev/sonar"
              - name: "SONARQUBE_JDBC_PASSWORD"
                valueFrom:  
                  secretKeyRef:  
                    name: postgres  
                    key: password
              ports:
              - containerPort: 9000
                protocol: TCP
      volumes:
        - name: sonar-data
          persistentVolumeClaim:
            claimName: efs-claim
